// Mocks generated by Mockito 5.0.17 from annotations
// in demo_project/test/app/repository/staff/staff_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:demo_project/data/network/network_api_service.dart' as _i2;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [NetworkApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkApiService extends _i1.Mock implements _i2.NetworkApiService {
  MockNetworkApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  _i3.Future<dynamic> getResponse(String? url, {String? token}) => (super
      .noSuchMethod(Invocation.method(#getResponse, [url], {#token: token}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> postResponse(String? url, Map<String, dynamic>? jsonBody,
          {String? token}) =>
      (super.noSuchMethod(
          Invocation.method(#postResponse, [url, jsonBody], {#token: token}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  dynamic returnResponse(_i4.Response? response) =>
      super.noSuchMethod(Invocation.method(#returnResponse, [response]));
}
